### ISSUE TITLE
Outdated information about iCloud drive data encryption

### ISSUE THREAD

**Issue by quackerex** [beerisgood/Smartphone_Security#5]
> iCloud Drive data encrypted at rest on server? [Reddit](https://www.reddit.com/r/privacy/comments/im7we1/icloud_drive_data_encrypted_at_rest_on_server/g3yc7p6/)

This information is outdated after apple introduced Advanced Data Protection for iCloud. 
[Maybe link to this page instead](https://support.apple.com/HT202303).

**Comment by beerisgood** [comment]
Nice find!

Solved with https://github.com/beerisgood/Smartphone_Security/commit/0da71c05225b6451a923704245bae0573fc0fef6
